"""empty message

Revision ID: 24735d4ba243
Revises: 5b365749fcb3
Create Date: 2021-01-24 10:00:00.534245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24735d4ba243'
down_revision = '5b365749fcb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_catalogues', sa.Column('property_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_catalogues', 'property_id')
    # ### end Alembic commands ###
