"""empty message

Revision ID: 5b365749fcb3
Revises: 18dcf8af38a3
Create Date: 2021-01-21 14:31:27.623226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b365749fcb3'
down_revision = '18dcf8af38a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_catalogues', sa.Column('currency', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_catalogues', 'currency')
    # ### end Alembic commands ###