"""empty message

Revision ID: 774831c92525
Revises: a3f0da2a05a3
Create Date: 2021-02-01 10:40:17.271534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '774831c92525'
down_revision = 'a3f0da2a05a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_association')
    op.drop_table('tag')
    op.drop_table('statement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('statement_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('search_text', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('conversation', sa.VARCHAR(length=32), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('in_response_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('search_in_response_to', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('persona', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='statement_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tag_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tag_pkey'),
    sa.UniqueConstraint('name', name='tag_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tag_association',
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('statement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], name='tag_association_statement_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='tag_association_tag_id_fkey')
    )
    # ### end Alembic commands ###