"""empty message

Revision ID: b5fbb12d6994
Revises: 
Create Date: 2021-02-17 11:35:19.575162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5fbb12d6994'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comapny_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.Column('phone_number_encrypted', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hook', sa.String(length=256), nullable=False),
    sa.Column('welcome_msg', sa.Text(), nullable=True),
    sa.Column('type_of_business', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hook')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_api_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.Column('host', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('api_company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_company_id'], ['user_api_companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host')
    )
    op.create_table('user_api_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=256), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('requirement_header', sa.Text(), nullable=True),
    sa.Column('requirement_body', sa.Text(), nullable=True),
    sa.Column('requirement_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_catalogues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('property_name', sa.String(length=256), nullable=True),
    sa.Column('catalogue_image', sa.String(length=256), nullable=True),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('id_ru', sa.Integer(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_catalogues')
    op.drop_table('user_api_urls')
    op.drop_table('user_api_details')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('user_api_companies')
    # ### end Alembic commands ###
