from google_trans_new import google_translator 


class LanguageConversion():
    translator = google_translator()

    # italian to english
    en_it = {
        "Hi welcome to HOLIDAY HOMES AND VILLAS IN MARINA DI NOTO, SICILY.\nRelevant Accommodations\nDiscover our accommodations in Marina di Noto (Syracuse), near the sea\n\nHow can I help you?":"Salve benvenuto a CASE E VILLE VACANZA A MARINA DI NOTO, SICILIA. \ NAlloggio di rilievo \ nScopri i nostri alloggi a Marina di Noto (Siracusa), vicino al mare \ n \ nCome posso aiutarti?",
        "room":"camera", 
        "holiday":"vacanza", 
        "villa":"villa", 
        "accommodation":"alloggio", 
        "tour":"tour", 
        "sea":"mare", 
        "beaches":"spiagge", 
        "start":"inizio", 
        "hi":"Ciao", 
        "hoi":"Ciao", 
        "help":"Aiuto", 
        "support":"supporto", 
        "Calendar":"Calendario",
        "From":"A partire dal",
        "how":"Come", 
        "Wrong answer, kindly send":"Risposta sbagliata, invia gentilmente", 
        "only 0 to see more":"solo 0 per vedere di più", 
        "or":"o", 
        "single alphabet character to select eg. a or b":"singolo carattere alfabetico da selezionare ad es. a o b", 
        "Wrong email, kindly send the details again in first_name,last_name,email format":"E-mail errata, invia di nuovo i dettagli in formato nome, cognome, e-mail", 
        "Wrong date or format, kindly send checkin date in":"Data o formato errati, inviare gentilmente la data di check-in", 
        "format only":"solo formato",  
        "only number eg.":"solo numero es.", 
        "Kindly start from the beginning. You can start with say 'hi'":"Si prega di iniziare dall'inizio. Puoi iniziare dicendo 'ciao'", 
        "For reference":"Per riferimento", 
        "What is your expected":"Qual è il tuo previsto", 
        "Check-in date?":"Data di arrivo?", 
        "format":"formato", 
        "how many days would you like to stay?":"quanti giorni vorresti restare?", 
        "reply only number eg.":"risposta solo numero es.", 
        "Wrong date. Must be greater than today.":"Data sbagliata. Deve essere maggiore di oggi.", 
        "Kindly start from the beginning":"Si prega di iniziare dall'inizio", 
        "How many persons [adults and children, please exclude babies] will stay?":"Quante persone [adulti e bambini, escludere i neonati] rimarranno?", 
        "reply only number":"risposta solo numero", 
        "eg.":"per esempio.", 
        "rooms":"camere", 
        "bath":"bagno", 
        "Min/Max Guests":"Ospiti min / max", 
        "For more details":"Per ulteriori dettagli", 
        "kindly click":"clicca gentilmente", 
        "Price per night":"Prezzo per notte", 
        "Do you want to book this property?":"Vuoi prenotare questa struttura?", 
        "reply":"rispondere", 
        "If you want to see more properties?":"Se vuoi vedere più proprietà?", 
        "Sorry right now no more property available as per your search.":"Siamo spiacenti in questo momento non più proprietà disponibili come da ricerca", 
        "To make a selection":"Per fare una selezione", 
        "Kindly reply":"Gentilmente rispondi", 
        "Kindly select from above list":"Si prega di selezionare dall'elenco sopra", 
        "Kindly start from the beginning. Type Support to view the Mobile Services menu. You can start with say 'hi'":"Si prega di iniziare dall'inizio. Digitare Supporto per visualizzare il menu Servizi mobili. Puoi iniziare dicendo 'ciao'", 
        "Congratulation you have selected this property":"Congratulazioni, hai selezionato questa proprietà", 
        "Reservation details":"Dettagli della prenotazione", 
        "Nights":"Notti", 
        "Adults":"Adulte o Adulti", 
        "Children":"Bambine o Bambini", 
        "Total amount":"Importo totale", 
        "after discount and charges":"dopo lo sconto e le spese", 
        "Discounted Price":"Prezzo scontato",
        "cleaning and tourist tax":"pulizia e tassa di soggiorno", 
        "Optional services":"Servizi opzionali", 
        "Total":"Totale", 
        "Deposit to pay now":"Deposito da pagare ora", 
        "Balance":"Equilibrio", 
        "To complete the booking we need":"Per completare la prenotazione abbiamo bisogno", 
        "Your Details":"I tuoi dettagli", 
        "Kindly reply your":"Gentilmente rispondi al tuo", 
        "Full Name and Email":"Nome completo ed e-mail", 
        "in following format and no space":"nel seguente formato e senza spazio", 
        "First Name,Last Name,Email":"Nome,Cognome,Email", 
        "Congratulation your booking request has been registered. Your can login here":"Congratulazioni, la tua richiesta di prenotazione è stata registrata. Puoi accedere qui", 
        "How do you want to pay?":"Come vuoi pagare?", 
        "reply a or b":"rispondere a o b", 
        "To complete booking click this url":"Per completare la prenotazione fare clic su questo URL", 
        "I only know about beautiful rooms in Sicily, sorry!":"Conosco solo belle camere in Sicilia, mi dispiace!"
        }

    it_en = {
        "Salve benvenuto a CASE E VILLE VACANZA A MARINA DI NOTO, SICILIA. \ NAlloggio di rilievo \ nScopri i nostri alloggi a Marina di Noto (Siracusa), vicino al mare \ n \ nCome posso aiutarti?":"Hi welcome to HOLIDAY HOMES AND VILLAS IN MARINA DI NOTO, SICILY.\nRelevant Accommodations\nDiscover our accommodations in Marina di Noto (Syracuse), near the sea\n\nHow can I help you?",
        "camera":"room", 
        "vacanza":"holiday", 
        "villa":"villa", 
        "alloggio":"accommodation", 
        "tour":"tour", 
        "mare":"sea", 
        "spiagge":"beaches", 
        "inizio":"start", 
        "Ciao":"hi", 
        "Aiuto":"help", 
        "supporto":"support",
        "Calendario":"Calendar", 
        "A partire dal":"From",
        "come":"how", 
        "Risposta sbagliata, invia gentilmente":"Wrong answer, kindly send", 
        "solo 0 per vedere di più":"only 0 to see more", 
        "o":"or", 
        "singolo carattere alfabetico da selezionare ad es. a o b":"single alphabet character to select eg. a or b", 
        "E-mail errata, invia di nuovo i dettagli in formato nome, cognome, e-mail":"Wrong email, kindly send the details again in first_name,last_name,email format", 
        "Data o formato errati, inviare gentilmente la data di check-in":"Wrong date or format, kindly send checkin date in", 
        "solo formato":"format only",  
        "solo numero es.":"only number eg.", 
        "Si prega di iniziare dall'inizio. Puoi iniziare dicendo 'ciao'":"Kindly start from the beginning. You can start with say 'hi'", 
        "Per riferimento":"For reference", 
        "Qual è il tuo previsto":"What is your expected", 
        "Data di arrivo?":"Check-in date?", 
        "formato":"format", 
        "quanti giorni vorresti restare?":"how many days would you like to stay?", 
        "risposta solo numero es.":"reply only number eg.", 
        "Data sbagliata. Deve essere maggiore di oggi.":"Wrong date. Must be greater than today.", 
        "Si prega di iniziare dall'inizio":"Kindly start from the beginning", 
        "Quante persone [adulti e bambini, escludere i neonati] rimarranno?":"How many persons [adults and children, please exclude babies] will stay?", 
        "risposta solo numero":"reply only number", 
        "per esempio.":"eg.", 
        "camere":"rooms", 
        "bagno":"bath", 
        "Ospiti min / max":"Min/Max Guests", 
        "Per ulteriori dettagli":"For more details", 
        "clicca gentilmente":"kindly click", 
        "Prezzo per notte":"Price per night", 
        "Vuoi prenotare questa struttura?":"Do you want to book this property?", 
        "rispondere":"reply", 
        "Se vuoi vedere più proprietà?":"If you want to see more properties?", 
        "Siamo spiacenti in questo momento non più proprietà disponibili come da ricerca":"Sorry right now no more property available as per your search.", 
        "Per fare una selezione":"To make a selection", 
        "Gentilmente rispondi":"Kindly reply", 
        "Si prega di selezionare dall'elenco sopra":"Kindly select from above list", 
        "Si prega di iniziare dall'inizio. Digitare Supporto per visualizzare il menu Servizi mobili. Puoi iniziare dicendo 'ciao'":"Kindly start from the beginning. Type Support to view the Mobile Services menu. You can start with say 'hi'", 
        "Congratulazioni, hai selezionato questa proprietà":"Congratulation you have selected this property", 
        "Dettagli della prenotazione":"Reservation details", 
        "Notti":"Nights", 
        "Adulte o Adulti":"Adults", 
        "Bambine o Bambini":"Children", 
        "Importo totale":"Total amount", 
        "dopo lo sconto e le spese":"after discount and charges", 
        "Prezzo scontato":"Discounted Price", 
        "pulizia e tassa di soggiorno":"cleaning and tourist tax",
        "Servizi opzionali":"Optional services", 
        "Totale":"Total", 
        "Deposito da pagare ora":"Deposit to pay now", 
        "Equilibrio":"Balance", 
        "Per completare la prenotazione abbiamo bisogno":"To complete the booking we need", 
        "I tuoi dettagli":"Your Details", 
        "Gentilmente rispondi al tuo":"Kindly reply your", 
        "Nome completo ed e-mail":"Full Name and Email", 
        "nel seguente formato e senza spazio":"in following format and no space", 
        "Nome,Cognome,Email":"First Name,Last Name,Email", 
        "Congratulazioni, la tua richiesta di prenotazione è stata registrata. Puoi accedere qui":"Congratulation your booking request has been registered. Your can login here", 
        "Come vuoi pagare?":"How do you want to pay?", 
        "rispondere a o b":"reply a or b", 
        "Per completare la prenotazione fare clic su questo URL":"To complete booking click this url", 
        "Conosco solo belle camere in Sicilia, mi dispiace!":"I only know about beautiful rooms in Sicily, sorry!"
        }

    # return the specific translated text
    # from_ first two char of lan
    # to first two char of lan
    def translate(self, from_, to, text):
        if from_ == 'en' and to == 'en':
            return text
        elif from_ == 'en' and to == 'it':
            if self.en_it.get(text) == None and self.en_it.get(text.capitalize) == None:
                translated_text = self.translator.translate(text, lang_src='en', lang_tgt='it')
            else:
                translated_text = self.en_it[text.capitalize] if self.en_it.get(text.capitalize) != None else self.en_it[text]
        elif from_ == 'it' and to == 'en':
            if self.it_en.get(text) == None and self.it_en.get(text.capitalize) == None:
                translated_text = self.translator.translate(text, lang_src='it', lang_tgt='en')
            else:
                translated_text = self.it_en[text.capitalize] if self.it_en.get(text.capitalize) != None else self.it_en[text]

        return translated_text if translated_text != None else text